name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: echo "C:/Program Files/Git/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: |
          git version
          git-lfs version
          git lfs version
          echo "============"
          where git
          echo "============"
          where git-lfs
          echo "============"
          echo "Building Git LFS demo ..."
          cd build
          go build -o git-lfs.exe
          cd ..
          PATH="$(pwd)/build:$PATH"
          export PATH
          git-lfs version
          git lfs version
          echo "============"
          where git-lfs
          echo "============"
        shell: bash
